# Generated by Django 5.2.3 on 2025-07-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portfolios_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
