# Generated by Django 5.2.3 on 2025-07-04 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_portfolios_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portfolios_remaining',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('agent', 'Agent'), ('student', 'Student')], default='normal', max_length=10),
        ),
    ]
