# Generated by Django 5.2.3 on 2025-07-07 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add new fields to UserProfile for agent/student functionality
        migrations.AddField(
            model_name='userprofile',
            name='agent_commission_rate',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_total_earnings',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_pending_payments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_agent_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_payment_completed',
            field=models.BooleanField(default=False),
        ),

        # Create new models for agent-student workflow
        migrations.CreateModel(
            name='StudentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('student_username', models.CharField(max_length=150)),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Approval'), ('approved', 'Approved by Admin'), (
                    'rejected', 'Rejected by Admin'), ('activated', 'Student Activated Account')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='student_invitations', to='users.userprofile')),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='approved_invitations', to=settings.AUTH_USER_MODEL)),
                ('student_user', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.CreateModel(
            name='AgentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_count', models.IntegerField()),
                ('per_student_cost', models.DecimalField(
                    decimal_places=2, default=699.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), (
                    'failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(
                    blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(
                    blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='agent_payments', to='users.userprofile')),
                ('student_invitations', models.ManyToManyField(
                    related_name='agent_payments', to='users.studentinvitation')),
            ],
        ),

        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(
                    decimal_places=2, default=2999.0, max_digits=10)),
                ('discounted_price', models.DecimalField(
                    decimal_places=2, default=1499.0, max_digits=10)),
                ('amount_paid', models.DecimalField(
                    decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), (
                    'failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(
                    blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(
                    blank=True, max_length=500)),
                ('agent_commission', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='student_payments', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='commission_payments', to='users.userprofile')),
            ],
        ),

        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('student_invitation', 'Student Invitation'), (
                    'agent_payment', 'Agent Payment'), ('student_payment', 'Student Payment'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
