# Generated by Django 5.2.3 on 2025-07-07 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_agent_student_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('student_invitation', 'Student Invitation'), ('agent_payment', 'Agent Payment'), (
                'student_payment', 'Student Payment'), ('system', 'System Notification')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_commission_rate',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_pending_payments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_total_earnings',
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_agent_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='AgentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_count', models.IntegerField()),
                ('per_student_cost', models.DecimalField(
                    decimal_places=2, default=699.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), (
                    'failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(
                    blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(
                    blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='agent_payments', to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='agent_payment',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.agentpayment'),
        ),
        migrations.CreateModel(
            name='StudentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('student_username', models.CharField(max_length=150)),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Approval'), ('approved', 'Approved by Admin'), (
                    'rejected', 'Rejected by Admin'), ('activated', 'Student Activated Account')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='approved_invitations', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='student_invitations', to='users.userprofile')),
                ('student_user', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('agent', 'student_email')},
            },
        ),
        migrations.AddField(
            model_name='agentpayment',
            name='student_invitations',
            field=models.ManyToManyField(
                related_name='agent_payments', to='users.studentinvitation'),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='student_invitation',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studentinvitation'),
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(
                    decimal_places=2, default=2999.0, max_digits=10)),
                ('discounted_price', models.DecimalField(
                    decimal_places=2, default=1499.0, max_digits=10)),
                ('amount_paid', models.DecimalField(
                    decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), (
                    'failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(
                    blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(
                    blank=True, max_length=500)),
                ('agent_commission', models.DecimalField(
                    decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='commission_payments', to='users.userprofile')),
                ('portfolio', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='users.studentportfolio')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='student_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='student_payment',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studentpayment'),
        ),
    ]
