# Generated by Django 5.2.3 on 2025-07-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_agent_student_fields'),
        ('users', '0005_alter_adminnotification_options_and_more'),
    ]

    operations = [
    ]
