# Generated by Django 5.2.3 on 2025-07-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_adminnotification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnotification',
            name='related_user',
        ),
    ]
