# Generated by Django 5.2.4 on 2025-07-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_adminnotification_options_and_more'),
        ('users', '0005_merge_20250708_1729'),
        ('users', '0006_remove_adminnotification_related_user'),
    ]

    operations = [
    ]
