# Generated by Django 5.2.4 on 2025-07-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20250713_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentportfolio',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this portfolio has been viewed.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_template_changes',
            field=models.IntegerField(default=50),
        ),
    ]
